name: eyespark
description: A smart assistive AI navigation application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Camera
  camera: ^0.11.0+2

  # Text-to-Speech
  flutter_tts: ^4.0.2

  # Speech Recognition
  speech_to_text: ^7.0.0

  # Local storage
  shared_preferences: ^2.2.3

  # AI Object Detection
  google_mlkit_object_detection: ^0.15.0
  google_mlkit_commons: ^0.11.0

  # Permissions
  permission_handler: ^11.3.1

  # Bluetooth Low Energy
  flutter_blue_plus: ^1.35.11

  # Path utilities
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
